development:
  adapter: postgresql
  encoding: unicode
  database: talentwiz_development
  pool: 5
  username: loganhouston
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: talentwiz_test
  pool: 5
  username: loganhouston
  password: 
