# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91ce9c23a245013c87491224a4d2e9391d22f72dab345fbc0600b93326c2d59336d32737429e46832b71b4c8a8e7cdded5983e7d61e1c00b258d0e214223a3d9

test:
  secret_key_base: 5c8564651bdc5c9ef0e955adde5d48918b335b6dbac49005f1aa59cd98df4cea1b84da4476152a6bd3bef3c6e5ea5c0fd5f950b6c127ac5b612a8195ff166c96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
