default: 
  toolbar: false
    - bold italic underline | undo redo | image link
  plugins:
    - image
    - link
    - noneditable
  menubar: false

  # content_css: asset_path 'tinymce.sass'
  # noneditable_noneditable_class: "class_one"
  # noneditable_regexp: /\{\{[^\]]+\}\}/g

alternate:
  toolbar: false
  menubar: false
  statusbar: false
  plugins:
    - noneditable


  # mentions: 
  #   source: [
  #       { name: 'Tyra Porcelli' },
  #       { name: 'Brigid Reddish' },
  #       { name: 'Ashely Buckler' },
  #       { name: 'Teddy Whelan' }
  #       ]


