default: 
  toolbar: false
    - styleselect | bold italic underline | undo redo | image link
  plugins:
    - image
    - link
    - noneditable
  menubar: false

  content_css: asset_path 'tinymce.sass'
  # noneditable_noneditable_class: "class_one"
  # noneditable_regexp: /\{\{[^\]]+\}\}/g

alternate:
  selector: textarea.table-editor
  toolbar: false
  menubar: false
  statusbar: false


